// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Ix9MbqqIv11nBE34g0uC817m-1rnKKo',
    appId: '1:610609808364:web:76d33145e52b25c6a376c9',
    messagingSenderId: '610609808364',
    projectId: 'todore-42b9b',
    authDomain: 'todore-42b9b.firebaseapp.com',
    storageBucket: 'todore-42b9b.firebasestorage.app',
    measurementId: 'G-W6W9LG1HN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYPE2DIN5ytdlD85gKZJ8GcayeMVSQJ-4',
    appId: '1:610609808364:android:fc46c091dddc3d2ea376c9',
    messagingSenderId: '610609808364',
    projectId: 'todore-42b9b',
    storageBucket: 'todore-42b9b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJWiv8XmYx0jilyelAZz4ZDoWDm5dSZxs',
    appId: '1:610609808364:ios:8355889cc2cb7776a376c9',
    messagingSenderId: '610609808364',
    projectId: 'todore-42b9b',
    storageBucket: 'todore-42b9b.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJWiv8XmYx0jilyelAZz4ZDoWDm5dSZxs',
    appId: '1:610609808364:ios:8355889cc2cb7776a376c9',
    messagingSenderId: '610609808364',
    projectId: 'todore-42b9b',
    storageBucket: 'todore-42b9b.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6Ix9MbqqIv11nBE34g0uC817m-1rnKKo',
    appId: '1:610609808364:web:6f86e9f1e393fefaa376c9',
    messagingSenderId: '610609808364',
    projectId: 'todore-42b9b',
    authDomain: 'todore-42b9b.firebaseapp.com',
    storageBucket: 'todore-42b9b.firebasestorage.app',
    measurementId: 'G-WZ9CL2PCTP',
  );
}
